name: First Workflow
on: workflow_dispatch
jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print in MultiLine
        run: |
          echo "Firstline Output"
          echo "SecondLine Output"
      - name: Print GoodBye
        run: echo "Done - Bye!"
